/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-01-20 01:26:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mainpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/yuumi/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/yuumi/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698996710949L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Top Bar ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Bar -->\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Hero Section ======= -->\r\n");
      out.write("  <section id=\"hero\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"book_search\">\r\n");
      out.write("          <div>\r\n");
      out.write("             <input type=\"text\" placeholder=\"원하는 독서 후기를 검색해보세요!\">\r\n");
      out.write("             <button type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("  </section><!-- End Hero -->\r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("  <div id=\"heroCarousel\" data-bs-interval=\"5000\" class=\"carousel slide carousel-fade library_slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 1 -->\r\n");
      out.write("          <div class=\"carousel-item active test\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write("              <div class=\"carousel-content animate__animated animate__fadeInLeft\">\r\n");
      out.write("                  <div class=\"library_slide_inner\">\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                  </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 2 -->\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              <div class=\"carousel-content animate__animated animate__fadeInLeft\">\r\n");
      out.write("                  <div class=\"library_slide_inner\">\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                  </div>");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 3 -->\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              <div class=\"carousel-content animate__animated animate__fadeInLeft\">\r\n");
      out.write("                  <div class=\"library_slide_inner\">\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                        <div class=\"lb_row\">\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                              <div class=\"lb_content\">\r\n");
      out.write("                                   <div class=\"lb_icon\"><i class=\"fas fa-book-reader\"></i></div>\r\n");
      out.write("                                   <div class=\"lb_info\">\r\n");
      out.write("                                        <p><a href=\"#\">2.28 도서관</a></p>\r\n");
      out.write("                                        <p>대구광역시 중구 2-28길 9</p>\r\n");
      out.write("                                        <p>053-257-2280</p>\r\n");
      out.write("                                        <p>화~금 09:00~18:00, 토일 09:00~17:00</p>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>");
      out.write("\r\n");
      out.write("                        </div>");
      out.write("\r\n");
      out.write("                  </div>");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#heroCarousel\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon bx bx-left-arrow\" aria-hidden=\"true\">\r\n");
      out.write("              <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#heroCarousel\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon bx bx-right-arrow\" aria-hidden=\"true\">\r\n");
      out.write("              <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <ol class=\"carousel-indicators\" id=\"hero-carousel-indicators\"></ol>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= board Section ======= -->\r\n");
      out.write("    <section id=\"board\" class=\"board\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"b_inner\">\r\n");
      out.write("              <div class=\"b_title\">\r\n");
      out.write("                    <p>공지 게시판</p>\r\n");
      out.write("                    <a href=\"/noticeboard/notice_list\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"nb_list b_list\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p><a href=\"/noticeboard\">공지사항 제목</a></p>\r\n");
      out.write("                        <p>2024-01-17</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p><a href=\"/noticeboard\">공지사항 제목제목제목제목제목제목제목제목제목제목제목제목제목제목제목제목제목</a></p>\r\n");
      out.write("                        <p>2024-01-17</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p><a href=\"/noticeboard\">공지사항 제목</a></p>\r\n");
      out.write("                        <p>2024-01-17</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p><a href=\"/noticeboard\">공지사항 제목</a></p>\r\n");
      out.write("                        <p>2024-01-17</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p><a href=\"/noticeboard\">공지사항 제목</a></p>\r\n");
      out.write("                        <p>2024-01-17</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("              </div>\r\n");
      out.write("         </div> ");
      out.write("\r\n");
      out.write("         <div class=\"b_inner\">\r\n");
      out.write("              <div class=\"b_title\">\r\n");
      out.write("                    <p>자유 게시판</p>\r\n");
      out.write("                    <a href=\"/freeboard/board_list\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"fb_list b_list\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("         </div> ");
      out.write("\r\n");
      out.write("      </div> ");
      out.write("\r\n");
      out.write("    </section> <!-- End board Section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= review Section ======= -->\r\n");
      out.write("  <section id=\"review\" class=\"review portfolio\"> ");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("          <div class=\"rv_title\">후기 게시판</div>\r\n");
      out.write("          <div class=\"row portfolio-container\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\"><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("                  <img src=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\"> ");
      out.write("\r\n");
      out.write("                  <div class=\"portfolio-info\">\r\n");
      out.write("                      <h4>도서 이름</h4>\r\n");
      out.write("                      <p>지은이</p> ");
      out.write("\r\n");
      out.write("                      <a href=\"../../../resources/assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox preview-link\" ><i class=\"bx bx-plus\"></i></a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("      </div> ");
      out.write("\r\n");
      out.write("   </section><!-- End review Section -->\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Footer ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/waypoints/noframework.waypoints.js\"></script>\r\n");
      out.write("  <script src=\"../../../resources/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"../../../resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mainpage/index.jsp(245,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mainpage/index.jsp(245,20) '${freeBoardList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${freeBoardList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mainpage/index.jsp(245,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("freeboard");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                          <div>\r\n");
            out.write("                                <p><a href=\"/freeboard/board_one?board_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.board_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.board_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></p>\r\n");
            out.write("                                <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                               <p>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</p>\r\n");
            out.write("\r\n");
            out.write("                          </div>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/mainpage/index.jsp(249,34) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      // /WEB-INF/views/mainpage/index.jsp(249,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.board_createdAt}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
