/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-01-20 01:29:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reviewboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.multi.mini6.reviewboard.vo.ReviewVO;
import com.multi.mini6.reviewboard.vo.ReviewAttachVO;

public final class review_005flist3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.multi.mini6.reviewboard.vo.ReviewVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.multi.mini6.reviewboard.vo.ReviewAttachVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>게시판 목록</title>\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("    <link href=\"../../../resources/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("    <link href=\"../../../resources/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor CSS Files -->\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../../resources/assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Main CSS File -->\r\n");
      out.write("    <link href=\"../../../resources/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap JS (optional) -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery-3.7.1 -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        .logo-link {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-decoration: none; /* 링크 밑줄 제거 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-image {\r\n");
      out.write("            max-width: 300px; /* 로고 이미지 크기 조정 */\r\n");
      out.write("            height: auto; /* 이미지 높이 자동 조절 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-text {\r\n");
      out.write("            font-size: 24px; /* 로고 텍스트 크기 */\r\n");
      out.write("            font-weight: bold; /* 글씨 굵게 */\r\n");
      out.write("            color: #333; /* 글씨 색상 */\r\n");
      out.write("            /*margin-left: 5px; !* 이미지와 텍스트 간격 *!*/\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .row img {\r\n");
      out.write("            max-width: 200px;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $('.btn.btn-outline-secondary').click(function () {\r\n");
      out.write("\r\n");
      out.write("                console.log($(this).text());\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: \"review_search1\",\r\n");
      out.write("                    data: {\r\n");
      out.write("                        page: $(this).text(),\r\n");
      out.write("                        keyword: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\r\n");
      out.write("                    },\r\n");
      out.write("                    success: function (table) {\r\n");
      out.write("                        $('#result').html(table);\r\n");
      out.write("                        $('#keyword').val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function (error) {\r\n");
      out.write("                        console.error(error);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- ======= Top Bar ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Bar -->\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Breadcrumbs ======= -->\r\n");
      out.write("<section id=\"breadcrumbs\" class=\"breadcrumbs\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <h2>Setting</h2>\r\n");
      out.write("            <ol>\r\n");
      out.write("                <li><a href=\"../mainpage/index.jsp\">Home</a></li>\r\n");
      out.write("                <li>Setting</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</section><!-- End Breadcrumbs -->\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"yellow\">\r\n");
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("    <!-- 검색창과 버튼 -->\r\n");
      out.write("    <div class=\"row mb-3 justify-content-center\">\r\n");
      out.write("        <!-- 검색창 -->\r\n");
      out.write("        <div class=\"col-md-6 text-center\">\r\n");
      out.write("            <form action=\"review_search\" class=\"d-flex justify-content-center\">\r\n");
      out.write("                <input type=\"hidden\" name=\"page\" id=\"currentPage\" value=\"1\">\r\n");
      out.write("                <input name=\"keyword\" id=\"keyword\" class=\"form-control form-control-sm me-2\" type=\"search\"\r\n");
      out.write("                       placeholder=\"검색어를 입력하세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                       aria-label=\"Search\">\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-outline-success btn-sm\" type=\"submit\">검색</button>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Insert 버튼 -->\r\n");
      out.write("        <div class=\"col-md-6 text-end\">\r\n");
      out.write("            <a href=\"review_insert\" class=\"btn btn-primary\">게시글 작성</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("    <h3>독서후기게시판</h3>\r\n");
      out.write("    <div id=\"result\">\r\n");
      out.write("        ");

            //jsp에서 자동 import : 클릭하고 ctrl + shiftl + m
            List<ReviewVO> list = (List<ReviewVO>) request.getAttribute("list");

        
      out.write("\r\n");
      out.write("        <div class=\"container mt-4\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"col\">id</th>\r\n");
      out.write("                    <th scope=\"col\">제목</th>\r\n");
      out.write("                    <th scope=\"col\">내용</th>\r\n");
      out.write("                    <th scope=\"col\">작성일</th>\r\n");
      out.write("                    <th scope=\"col\">수정일</th>\r\n");
      out.write("                    <th scope=\"col\">조회수</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");

                    for (ReviewVO review : list) {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print(review.getReview_id());
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td><a href=\"review_one?review_id=");
      out.print(review.getReview_id());
      out.write('"');
      out.write('>');
      out.print(review.getReview_title());
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(review.getReview_content());
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(review.getReview_createdAt());
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(review.getReview_updatedAt());
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(review.getReview_views());
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr color=\"red\">\r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("        전체 게시물 수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개 <br>\r\n");
      out.write("        전체 페이지 수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개 <br>\r\n");
      out.write("        <div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("            ");

                int pages = (int) request.getAttribute("pages");//int(작) <--- Object(큰)
                String keyword = (String) request.getAttribute("keyword");

                for (int p = 1; p <= pages; p++) {
            
      out.write("\r\n");
      out.write("            <button class=\"btn btn-outline-secondary\">");
      out.print( p );
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr color=\"red\">\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ======= Footer ======= -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
